/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsgame;

import java.awt.Toolkit;

/**
 *
 * @author ESTRELLA
 */
public class howPlay extends javax.swing.JFrame {

    /**
     * Creates new form howPlay
     */
    public howPlay() {
        initComponents();
        this.setTitle("Bullshit Game: Instrucciones");
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/bsgame/img2/iconGame.png"))));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        volverBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(422, 790));
        setPreferredSize(new java.awt.Dimension(415, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(414, 730));

        jPanel1.setBackground(new java.awt.Color(52, 58, 64));
        jPanel1.setMaximumSize(new java.awt.Dimension(422, 700));
        jPanel1.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 193, 7));
        titleLabel.setText("¿Cómo se juega?");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(60, 30, 310, 47);

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(93, 95, 239));
        label1.setText("1.");
        jPanel1.add(label1);
        label1.setBounds(48, 124, 30, 34);

        Text1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text1.setText("<html>Al comenzar el juego, los jugadores recibirán la misma cantidad de cartas.<html>");
        Text1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text1);
        Text1.setBounds(96, 124, 281, 47);

        label2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(93, 95, 239));
        label2.setText("2.");
        jPanel1.add(label2);
        label2.setBounds(48, 199, 30, 34);

        Text2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text2.setText("<html> Un jugador podrá botar  de 1 a 4 cartas, dependiendo de su opción y su habilidad <html>");
        Text2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text2);
        Text2.setBounds(96, 199, 281, 62);

        Text3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text3.setText("<html> En la pantalla aparecerá  la carta que debe botar de su baraja y aquí es donde comienza el juego <html>");
        Text3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text3);
        Text3.setBounds(96, 289, 281, 64);

        label3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label3.setForeground(new java.awt.Color(93, 95, 239));
        label3.setText("3.");
        jPanel1.add(label3);
        label3.setBounds(48, 289, 30, 34);

        Text4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text4.setText("<html> Si el jugador decide hacer caso a la pantalla, entonces dirá la verdad y pasará, si no mentirá.<html>");
        Text4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text4);
        Text4.setBounds(96, 381, 281, 53);

        label4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label4.setForeground(new java.awt.Color(93, 95, 239));
        label4.setText("4.");
        jPanel1.add(label4);
        label4.setBounds(48, 381, 30, 34);

        Text5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text5.setText("<html> El siguiente jugador decidirá su futuro, si miente o dice la verdad, si cree que es un mentiroso apretará el botón, sino botará su cartas<html>");
        Text5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text5);
        Text5.setBounds(96, 462, 281, 61);

        label5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(93, 95, 239));
        label5.setText("5.");
        jPanel1.add(label5);
        label5.setBounds(48, 462, 30, 34);

        label6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label6.setForeground(new java.awt.Color(93, 95, 239));
        label6.setText("6.");
        jPanel1.add(label6);
        label6.setBounds(48, 551, 30, 34);

        Text6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Text6.setText("<html> Si acierta, el jugador anterior cogerá todas las cartas en la mesa.\n" +
            "Si no tendrá que coger todas las cartas.<html>");
        Text6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Text6);
        Text6.setBounds(96, 551, 281, 61);

        volverBtn.setBackground(new java.awt.Color(165, 166, 246));
        volverBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        jPanel1.add(volverBtn);
        volverBtn.setBounds(270, 620, 108, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsgame/img2/bg1.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(414, 700));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(howPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(howPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(howPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(howPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new howPlay().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
