/*
    CLASE MENU
        - Contiene el botón de jugar partida y sair del juego 
 */
package bsgame;


import java.awt.Toolkit;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Bullshit Game");
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("/bsgame/img2/iconGame.png"))));
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        exitGame = new javax.swing.JButton();
        btnHow = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        jButton2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jButton2.setText("PLAY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(414, 700));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 58, 64));
        jPanel1.setPreferredSize(new java.awt.Dimension(426, 684));
        jPanel1.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 193, 7));
        titleLabel.setText("BULLSHIT!");
        jPanel1.add(titleLabel);
        titleLabel.setBounds(80, 70, 253, 62);

        btnPlay.setBackground(new java.awt.Color(165, 166, 246));
        btnPlay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPlay.setText("Jugar");
        btnPlay.setBorder(null);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlay);
        btnPlay.setBounds(80, 400, 252, 48);

        exitGame.setBackground(new java.awt.Color(165, 166, 246));
        exitGame.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        exitGame.setText("Salir");
        exitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameActionPerformed(evt);
            }
        });
        jPanel1.add(exitGame);
        exitGame.setBounds(80, 540, 250, 48);

        btnHow.setBackground(new java.awt.Color(165, 166, 246));
        btnHow.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnHow.setText("¿Cómo Jugar?");
        btnHow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHowActionPerformed(evt);
            }
        });
        jPanel1.add(btnHow);
        btnHow.setBounds(80, 470, 250, 48);

        imgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsgame/img2/cartas.png"))); // NOI18N
        jPanel1.add(imgLabel);
        imgLabel.setBounds(140, 200, 128, 159);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bsgame/img2/bg1.png"))); // NOI18N
        jPanel1.add(bgLabel);
        bgLabel.setBounds(0, -20, 410, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        new configPlayer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitGameActionPerformed

    private void btnHowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHowActionPerformed
            // TODO add your handling code here:
           new howPlay().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_btnHowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton btnHow;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton exitGame;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
